### ISSUE TITLE
用这个规则无法更新google play商店软件

### ISSUE THREAD

**Issue by zxj930057911** [leosam1995/My_ACL_Rules#1]

**Comment by leosam1995** [comment]
恩 收到 马上尝试修复

**Comment by leosam1995** [comment]
被广告规则屏蔽了 我排除一下

**Comment by zxj930057911** [comment]
好的。修复完了我所有的线路是不是都要重新更新ACL？？我想能不能更新一次所有线路都好了？？

ABP rules of leosam1995 <notifications@github.com>于2017年2月14日周二 10:51写道：

**Comment by leosam1995** [comment]
恩 需要更新一下acl文件即可 前几天我加了大量第三方广告规则 可能有问题 我这几天没用play 结果没发现 正在排查中

**Comment by leosam1995** [comment]
已解决 是(^|\.)gvt1\.com$ 条目的事情 我写了30个acl 才排除 累死了  你更新一下即可

**Comment by zxj930057911** [comment]
马上！！！

ABP rules of leosam1995 <notifications@github.com>于2017年2月14日周二 11:57写道：

**Comment by zxj930057911** [comment]
正常了（更新完马上下载的时候不行，切换了线路再更新好了，再切回来正常了）

ABP rules of leosam1995 <notifications@github.com>于2017年2月14日周二 上午11:58写道：
