### ISSUE TITLE
去广告规则误杀 Gmail

### ISSUE THREAD

**Issue by hyxxsfwy** [leosam1995/My_ACL_Rules#3]
163 规则下面有这么一条：
```(chnl|dict|dictapp|ictvista|dictweb|dictword|mail)```

杀掉了所有包含 dict, mail 等关键字的 URL ……
这应该是自动转换脚本出问题了，请排查。

**Comment by leosam1995** [comment]
恩 已修复 是我编辑规则的时候干别的事了 结果给忘了
(^|\.)impservic\.(chnl|dict|dictapp|ictvista|dictweb|dictword|mail)\.youdao\.com$
本来是这个规则的 只编辑了中间 忘加两头了
