### ISSUE TITLE
对于bacAD.acl的疑问

### ISSUE THREAD

**Issue by tinyala** [leosam1995/My_ACL_Rules#4]
文件的开头部分使用了[proxy_all]，默认代理所有，但是文件后面又出现了[proxy_list]，这个岂不是多余的吗，既然已经在文件开头使用了[proxy_all]，为什么还需要单独指定一批需要代理的地址？

不知道是不是我理解错了，望指正，谢谢！

**Comment by leosam1995** [comment]
其实不加也行，加了也没啥关系。
主要以后2个原因：
一个是照顾telegram之类的使用ip的。
然后就是有些虽然是国内的站点，比如ipip.net 用来看是代理ip的。所以加了一下。

**Comment by tinyala** [comment]
是不是可以这么理解，后面的依次覆盖前面的规则：

比如[proxy_all]先定义所有都要走代理，[bypass_list]设定了一批不走代理的直连的规则，如果某些正则匹配的规则比较广，包含了某些实际需要代理的项，后面再用[proxy_list]单独列出来？

感谢耐心指正

**Comment by leosam1995** [comment]
这我倒没具体了解。
一般都是只要前面的规则匹配了，后面的正则就不验证了。
比如匹配了[bypass_list]中的正则。那么直接结束，[proxy_list]中的就不验证了。
上面的比如ipip.net 我都没在[bypass_list]中有匹配的。所以会在[proxy_list]得到匹配。
再比如baidu.com在[bypass_list]得到匹配，然后那么[proxy_list]就算有baidu.com 也不会进行匹配。
所以说 我把reject的放最前面，然后直连的，再代理的。
说白了就是从上往下面验证。匹配了，就停止验证。
有其他问题可以telegram找我.或者继续问一下

**Comment by h2y** [comment]
已经是全局默认代理了，我个人认为是没有必要额外定义代理规则的，毕竟越多正则会消耗越多的资源。

**Comment by MichaelHu55** [comment]
问题是，比如telegram,没有下面这条list。我手机上就连不上
