### ISSUE TITLE
建议黑名单部分由GFWList生成，而不是匹配常见TLD

### ISSUE THREAD

**Issue by BROBIRD** [leosam1995/My_ACL_Rules#5]
默认国外全部走代理还有匹配常见TLD是不是误伤有点太多了？谢谢。

**Comment by BROBIRD** [comment]
基于你原来的简单改了一个GFWList+详细ChinaIP+自定义白名单版的
https://raw.githubusercontent.com/BROBIRD/My_ACL_Rules/master/banAD.acl
请多多指教

**Comment by leosam1995** [comment]
不需要GFWList，GFWList好多用不上的，因为有默认代理兜着。只加入国内访问太卡的就行
然后常见TLD，误杀的话 感觉还好，没啥误杀的，如果有的话 请指出来。我加入只是觉得代理访问更快

然后详细的ChinaIP，我都那个是用这个http://ipblock.chacuo.net/ 网站你的 
看了一下 匹配的更详细的差不多，但能少2000条

**Comment by leosam1995** [comment]
然后我看了一下
#GFWList 关键字
(^|\.)(.*)64memo(.*)$
(^|\.)(.*)aHR0cHM6Ly95ZWNsLm5ldA(.*)$
(^|\.)(.*)freenet(.*)$
(^|\.)(.*)q=freedom(.*)$
(^|\.)(.*)q%3Dfreedom(.*)$
(^|\.)(.*)remembering_tiananmen_20_years(.*)$
(^|\.)(.*)search*safeweb(.*)$
(^|\.)(.*)q=triangle(.*)$
(^|\.)(.*)q%3DTriangle(.*)$
(^|\.)(.*)ultrareach(.*)$
(^|\.)(.*)ultrasurf(.*)
这是你的

但SSR的acl 只匹配域名 不匹配子网页啊  写了也没用

**Comment by BROBIRD** [comment]
我昨天找了一下SSR的ACL规则的写法，没找到它的匹配规则，就先按照gfwlist里的写进去了。国内IP的话我采用的是安卓版ssR自带的ACL里的那个。

**Comment by leosam1995** [comment]
嗯 我一开始也是用的自带的，结果发现新找的 跟内置的差不了多少，还少
我参考的是https://www.zhaoj.in/read-3938.html

**Comment by BROBIRD** [comment]
玄学了，我这规则http://ipblock.chacuo.net/都打不开
